name: RVaults
version: '1.0'
main: net.weesli.rvaults.RVaults
api-version: '1.13'
author: Weesli
softdepend: [Vault]
commands:
  rstorage:
    description: main command for storage commands
  storage:
    description: main command for storage commands


permissions:
  rvaults.admin:
    default: op